require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.3

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Max: 200

CyclomaticComplexity:
  Enabled: false

PerceivedComplexity:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

SkipsModelValidations:
  Enabled: false

Style/StringConcatenation:
  Enabled: false
# Rails/FilePath:
#   EnforcedStyle: arguments

convention:Metrics/BlockLength:
  Max: 70
